//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Tool.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_ToolTYPE                    130
#define IDD_FORM                        310
#define IDD_DIALOG1                     312
#define TAB_TERRAIN                     318
#define TAB_MESH                        320
#define TAB_EFFECT                      322
#define TAB_NavMesh                     324
#define BUTTON_Load_Scene               1000
#define LIST_PROTOTYPE                  1001
#define EDIT_CAMPOS_X                   1002
#define EDIT_CAMPOS_Y                   1003
#define EDIT_CAMPOS_Z                   1004
#define EDIT_NEAR                       1005
#define EDIT_FAR                        1006
#define EDIT_FOV                        1007
#define BUTTON_Save_Scene               1008
#define Button_Create                   1010
#define Button_Terrain_Create           1010
#define TAB_Form_Main                   1014
#define Radio_Render_Solid              1027
#define Radio_Render_Wireframe          1028
#define Terrain_List_Texture            1029
#define Edit_Vertices_X                 1030
#define Group_VIBuffer                  1031
#define Edit_Vertices_Z                 1032
#define Text_VerticesX                  1033
#define Text_VerticesZ                  1034
#define Pic_Terrain                     1035
#define Edit_Size_X                     1036
#define Text_SizeX                      1037
#define Edit_Size_Y                     1038
#define Edit_Size_Z                     1038
#define Text_SizeY                      1039
#define Edit_Tex_U                      1040
#define Text_TexU                       1041
#define Edit_Tex_V                      1042
#define Text_TexV                       1043
#define Edit_StartPos_X                 1044
#define Edit_StartPos_Y                 1045
#define Edit_StartPos_Z                 1046
#define List_Model                      1047
#define List_Form_Animations            1048
#define Button_Mesh_Create              1049
#define List_Animation                  1050
#define Text_Animations                 1051
#define Edit_ObjectName                 1052
#define Group_Position                  1063
#define Edit_Poisiton_X                 1064
#define Edit_Position_Y                 1065
#define Edit_Position_Z                 1066
#define Text_ObjectList                 1067
#define Text_ObjectAnimation            1068
#define Group_Scale                     1069
#define Group_Rotation                  1070
#define Edit_Scale_X                    1071
#define Edit_Scale_Y                    1072
#define Edit_Scale_Z                    1073
#define Edit_Rotation_X                 1074
#define Edit_Rotation_Y                 1075
#define Edit_Rotation_Z                 1076
#define Edit_SceneName                  1077
#define Button_Delete                   1078
#define Edit_Point1_X                   1079
#define Edit_Point2_X                   1080
#define Edit_Point3_X                   1081
#define Edit_Point1_Y                   1082
#define Edit_Point2_Y                   1083
#define Edit_Point3_Y                   1084
#define Edit_Point1_Z                   1085
#define Edit_Point2_Z                   1086
#define Edit_Point3_Z                   1087
#define Group_Point1                    1088
#define Group_Point2                    1089
#define Group_Point3                    1090
#define Check_Picking                   1093
#define Edit_TextureName                1094
#define Button_NavMesh_Load             1096
#define Button_NavMesh_Save             1097
#define Text_Scene_name                 1100
#define Edit_CullingRadius              1102
#define Eidt_FileName                   1104
#define Radio_AABB                      1106
#define Radio_OBB                       1107
#define Radio_Sphere                    1108
#define Radio_None                      1109
#define Edit_Collider_CenterX           1110
#define Edit_Collider_CenterY           1111
#define Edit_Collider_CenterZ           1112
#define Edit_Collider_ExtX              1113
#define Edit_Collider_ExtY              1114
#define Edit_Collider_ExtZ              1115
#define Button_ColliderActive           1116
#define IDC_LIST1                       1117
#define Button_NavDelete                1118
#define Edit_Collider_Radius            1119
#define Edit_Collider_RotX              1120
#define Edit_Collider_RotY              1121
#define Edit_Collider_RotZ              1122
#define Edit_OnePoint_X                 1123
#define Edit_OnePoint_Y                 1124
#define Edit_OnePoint_Z                 1125
#define Edit_Nav1X                      1126
#define Edit_Nav1Y                      1127
#define IDC_EDIT1                       1127
#define Edit_Nav1Z                      1128
#define IDC_BUTTON1                     1128
#define Edit_Nav2X                      1129
#define Edit_Nav2Y                      1130
#define Edit_Nav2Z                      1131
#define Edit_Nav3X                      1132
#define Edit_Nav3Y                      1133
#define Edit_Nav3Z                      1134

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        326
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1129
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
